services:
  stats-db:
    image: postgres:16.1
    container_name: stats-db
    ports:
      - "7432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=stats
      - POSTGRES_DB=stats-db
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 10s
      retries: 15
  user-db:
    image: postgres:16.1
    container_name: user-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=user-db
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 10s
      retries: 15

  event-db:
    image: postgres:16.1
    container_name: event-db
    ports:
      - "4432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=event
      - POSTGRES_DB=event-db
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 10s
      retries: 15

  request-db:
    image: postgres:16.1
    container_name: request-db
    ports:
      - "3432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=request
      - POSTGRES_DB=request-db
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 10s
      retries: 15

  comment-db:
    image: postgres:16.1
    container_name: comment-db
    ports:
      - "2432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=comment
      - POSTGRES_DB=comment-db
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 10s
      retries: 15