grpc:
  server:
    port: 0
    security:
      enabled: false
  client:
    collector:
      address: 'discovery:///collector'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
spring:
  kafka:
    producer:
      properties:
        bootstrap-servers: localhost:9092
        key-serializer: org.apache.kafka.common.serialization.LongSerializer
        value-serializer: ru.practicum.ewm.serializer.AvroSerializer

collector:
  topic:
    user-action: stats.user-actions.v1