server:
  port: 8080

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user_service_route
          uri: lb://user-service
          predicates:
            - Path=/users/**,/admin/users/**
        - id: event_service_route
          uri: lb://event-service
          predicates:
            - Path=/events/**,/admin/events/**,/users/*/events/**
        - id: request_service_route
          uri: lb://request-service
          predicates:
            - Path=/users/*/requests/**
        - id: comment_service_route
          uri: lb://comment-service
          predicates:
            - Path=/comments/**,/admin/comments/**,/users/*/comments/**
        - id: category_service_route
          uri: lb://category-service
          predicates:
            - Path=/categories/**,/admin/categories/**
        - id: compilation_service_route
          uri: lb://compilation-service
          predicates:
            - Path=/compilations/**,/admin/compilations/**