server:
  port: 0
spring:
  application:
    name: stats-server
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        hibernate:
          format_sql: true
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:7432/stats-db
    driver-class-name: "org.postgresql.Driver"
    username: stats
    password: password